name: Build Heltec V4 Web Monitor Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'repeater-mqtt-meshcoretel-*'

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      OFFICIAL_MESHCORE_VERSION: ${{ vars.OFFICIAL_MESHCORE_VERSION }}
      PLATFORMIO_BUILD_FLAGS: -UMQTT_DEBUG
    steps:

      - name: Clone Repo
        uses: actions/checkout@v6

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-environment

      - name: Build Heltec V4 Firmware
        run: /usr/bin/env bash build.sh build-firmware heltec_v4_repeater_mqtt

      - name: Upload Workflow Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: heltec-v4-web-monitor-firmware
          path: out

      - name: Create Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Heltec V4 Web Monitor ${{ env.RELEASE_VERSION }}
          body: ""
          draft: true
          files: out/*
